// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAviiHhpxkORUv_QAaXLNmU55g8J8rfT00',
    appId: '1:937615289579:web:76f706e111b2c0d8c0a2ae',
    messagingSenderId: '937615289579',
    projectId: 'renalizapp-2023',
    authDomain: 'renalizapp-2023.firebaseapp.com',
    storageBucket: 'renalizapp-2023.appspot.com',
    measurementId: 'G-GKBKNXN594',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdc_iDHs6vUelgao-jFOPAYJIHivrG5SI',
    appId: '1:937615289579:android:5954b6c57e134256c0a2ae',
    messagingSenderId: '937615289579',
    projectId: 'renalizapp-2023',
    storageBucket: 'renalizapp-2023.appspot.com',
  );
}