// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAypsjGbLvWfccG-45jZ1AyKNSEhUa5qgc',
    appId: '1:150217668394:web:96acfef1e6ce6a53d41053',
    messagingSenderId: '150217668394',
    projectId: 'renalizapp-dev-2023-396503',
    authDomain: 'renalizapp-dev-2023-396503.firebaseapp.com',
    storageBucket: 'renalizapp-dev-2023-396503.appspot.com',
    measurementId: 'G-BK6NYTG137',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv5ZSvpGlCw5KhMF4U2oBd2RSGIVSA2-k',
    appId: '1:150217668394:android:30f8714fb78e1280d41053',
    messagingSenderId: '150217668394',
    projectId: 'renalizapp-dev-2023-396503',
    storageBucket: 'renalizapp-dev-2023-396503.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqrgyimEXPoys_Ec2iB0jhQeesz8_5D9M',
    appId: '1:150217668394:ios:b6d6648d3648b131d41053',
    messagingSenderId: '150217668394',
    projectId: 'renalizapp-dev-2023-396503',
    storageBucket: 'renalizapp-dev-2023-396503.appspot.com',
    iosClientId: '150217668394-4fflv4t4kpo7mj8jrqphne5vc769emmv.apps.googleusercontent.com',
    iosBundleId: 'app.dportillo.renalizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqrgyimEXPoys_Ec2iB0jhQeesz8_5D9M',
    appId: '1:150217668394:ios:3c9128d224e71f9ad41053',
    messagingSenderId: '150217668394',
    projectId: 'renalizapp-dev-2023-396503',
    storageBucket: 'renalizapp-dev-2023-396503.appspot.com',
    iosClientId: '150217668394-8ifqtbq43c2sscemt3h3jn8e62f5gaup.apps.googleusercontent.com',
    iosBundleId: 'app.dportillo.renalizapp.RunnerTests',
  );
}
